services:
  backend:
    build:
      context: node
      args:
        - NODE_ENV=development
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run build