services:
  backend:
    container_name: backend
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev