services:
  backend:
    build:
      context: ../node
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    # # depends_on:
    # #   - mongo
    #   - rabbitmq
    ports:
      - 82:3000
    environment:
      - PORT=3000
    command: npm run start
    # restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME= mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD= secret
    volumes:
      - mongo-db:/data/db
      
  rabbitmq:
    image: rabbitmq:3.10.8-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 81:15672
    volumes:
        - /var/lib/rabbitmq/
        - /var/log/rabbitmq
        
volumes:
  mongo-db: